server:
  port: 8081
#  servlet:
#    context-path: /ewbfs
spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.SQLServer2012Dialect
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

  datasource: 
    username: root
    password:
    url: jdbc:mysql://localhost:3306/EWBFS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost
#          issuer-uri: http://localhost

eureka:
  client:
    serviceUrl:
      defaultZone: ${localhost}
  instance:
    preferIpAddress: true

services:
  hr: 'http://localhostr'
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

